// ------------------------------------
// Error Code
// ------------------------------------
export const ERROR_STATUS_NULL = 0
export const ERROR_INFO_UNKNOWN = 1000
export const ERROR_LICENSE_PGAE = 1001
export const ERROR_ACCOUNT_FREEZE = 1002
export const ERROR_GROUP_MASTER_ONLY = 1011
export const ERROR_USER_NAME_UNIQUE = 1022
export const ERROR_USER_EMAIL_UNIQUE = 1026
export const ERROR_SIGN_ACCESSTOKEN_NULL = 1031
export const ERROR_LOGINNAME_REQUIRED = 1032
export const ERROR_LOGINPASS_REQUIRED = 1033
export const ERROR_LOGINVALID_FAIL = 1034

export const ERROR_UPLOAD_FILESIZE_LARGEMAX = 1101
export const ERROR_UPLOAD_FILE_MIMETYPE = 1102
export const ERROR_UPLOAD_FLAG_NULL = 1103
export const ERROR_UPLOAD_NOT_FILE = 1104
export const ERROR_UPLOAD_DAY_MAXNUM = 1105
export const ERROR_UPLOADFILE_STORE_TYPE = 1106
export const ERROR_UPLOADFILE_NAME_UNIQUE = 1107
export const ERROR_DOWNLOAD_LEVEL_FLAG = 1111

export const ERROR_VALID_GROUPNAME_REQUIRED = 1411
export const ERROR_REMOVE_GROUP_USER_EXISTS = 1412
export const ERROR_BYLOND_LEVEL_OPERATION = 1413
export const ERROR_LICENSE_FLAG_OPERATION = 1414
export const ERROR_VALID_GROUP_REQUIRED = 1415
export const ERROR_VALID_GROUP_NOEXISTS = 1416
export const ERROR_VALID_USERNAME_OCCUPY = 1417

export const ERROR_VALID_USERNAME_REQUIRED = 1421
export const ERROR_VALID_USERNAME_FORMAT = 1422
export const ERROR_VALID_PASSWORD_REQUIRED = 1423
export const ERROR_VALID_PASSWORD_FORMAT = 1424
export const ERROR_VALID_EMAIL_REQUIRED = 1425
export const ERROR_VALID_EMAIL_FORMAT = 1426
export const ERROR_VALID_PHONE_REQUIRED = 1427
export const ERROR_VALID_PHONE_FORMAT = 1428
export const ERROR_VALID_NICKNAME_REQUIRED = 1429
export const ERROR_VALID_NICKNAME_FORMAT = 1430
export const ERROR_VALID_CHOOSEONE_MORE = 1431

export const ERROR_RETRIEVE_NOT_SEND_CONTINUE = 1501
export const ERROR_RETRIEVE_VALID_FAIL = 1502
export const ERROR_RETRIEVE_VALID_TIMEOUT = 1503
