// ------------------------------------
// Error Message
// ------------------------------------
export const ERROR_STATUS_NULL = 'Request Success!'
export const ERROR_INFO_UNKNOWN = '服务器异常'
export const ERROR_LICENSE_PGAE = '您没有权限访问该页面'
export const ERROR_ACCOUNT_FREEZE = '您的账号已被冻结'
export const ERROR_GROUP_MASTER_ONLY = '只能创建一个顶级组'
export const ERROR_USER_NAME_UNIQUE = '用户名已存在'
export const ERROR_USER_EMAIL_UNIQUE = '邮箱地址已存在'
export const ERROR_USER_PHONE_UNIQUE = '手机号已存在'
export const ERROR_SIGN_ACCESSTOKEN_NULL = '尚未登录或登录已失效'
export const ERROR_LOGINNAME_REQUIRED = '登录用户名不能为空'
export const ERROR_LOGINPASS_REQUIRED = '登录密码不能为空'
export const ERROR_LOGINVALID_FAIL = '用户名密码错误'

export const ERROR_UPLOAD_FILESIZE_LARGEMAX = '上传文件超过最大值 %s.'
export const ERROR_UPLOAD_FILE_MIMETYPE = '上传文件类型不许可. [%s]'
export const ERROR_UPLOAD_FLAG_NULL = '您没有上传权限.'
export const ERROR_UPLOAD_NOT_FILE = '请选择上传文件!'
export const ERROR_UPLOAD_DAY_MAXNUM = '上传文件超过当日最大数 %s.'
export const ERROR_UPLOADFILE_STORE_TYPE = '上传文件Store类型不存在.'
export const ERROR_UPLOADFILE_NAME_UNIQUE = '文件名已存在'
export const ERROR_DOWNLOAD_LEVEL_FLAG = '您所在的用户组没有下载该文件的权限'

export const ERROR_VALID_GROUPNAME_REQUIRED = '用户组名称不能为空'
export const ERROR_REMOVE_GROUP_USER_EXISTS = '无法删除，该用户组下存在用户，请先移除或转移'
export const ERROR_BYLOND_LEVEL_OPERATION = '您无法对比您等级高或平级的用户进行操作'
export const ERROR_LICENSE_FLAG_OPERATION = '您没有操作权限'
export const ERROR_VALID_GROUP_REQUIRED = '用户组不能为空'
export const ERROR_VALID_GROUP_NOEXISTS = '选择的用户组不存在'
export const ERROR_VALID_USERNAME_OCCUPY = '%s已占用，请换一个'

export const ERROR_VALID_USERNAME_REQUIRED = '用户名不能为空'
export const ERROR_VALID_USERNAME_FORMAT = '%s格式错误，%s'
export const ERROR_VALID_PASSWORD_REQUIRED = '密码不能为空'
export const ERROR_VALID_PASSWORD_FORMAT = '%s密码格式错误，%s'
export const ERROR_VALID_EMAIL_REQUIRED = '邮箱地址不能为空'
export const ERROR_VALID_EMAIL_FORMAT = '邮箱地址格式错误'
export const ERROR_VALID_PHONE_REQUIRED = '手机号不能为空'
export const ERROR_VALID_PHONE_FORMAT = '手机号格式错误'
export const ERROR_VALID_NICKNAME_REQUIRED = '昵称不能为空'
export const ERROR_VALID_NICKNAME_FORMAT = '昵称格式错误，%s'
export const ERROR_VALID_CHOOSEONE_MORE = '%s 必须设置一个'

export const ERROR_VAILD_WEBSITE_FORMAT = '%s 不是个正确的网址'
export const ERROR_VAILD_INTRO_BEYOND = '%s 超出最大字符限制'

export const ERROR_RETRIEVE_NOT_SEND_CONTINUE = '请不要连续发送，间隔为60秒'
export const ERROR_RETRIEVE_VALID_FAIL = '验证码错误'
export const ERROR_RETRIEVE_VALID_TIMEOUT = '验证码超时'